run_dir: "."
max_concurrent_downloads: 4
held_out_subreddits:
  - 3dprinting
  - accounting
  - advice
  - androiddev
  - anxiety
  - asoiaf
  - atlanta
  - baseball
  - bitcoin
  - blackops4
  - bloodborne
  - canada
  - cars
  - christianity
  - comicbooks
  - criticalrole
  - cryptocurrency
  - dbzdokkanbattle
  - decidingtobebetter
  - depression
  - destinythegame
  - dndnext
  - dogtraining
  - elitedangerous
  - fashionreps
  - fifa
  - forhonor
  - fortnite
  - freefolk
  - gorillaz
  - heroesofthestorm
  - holdmybeer
  - horror
  - investing
  - joerogan
  - kingdomhearts
  - knives
  - learnprogramming
  - legaladvice
  - marvelstudios
  - mma
  - monsterhunterworld
  - mtb
  - news
  - nfl
  - nostupidquestions
  - occult
  - overwatch
  - paranormal
  - pcgaming
  - personalfinance
  - personalfinancecanada
  - philosophy
  - pokemongo
  - poker
  - portland
  - raspberry_pi
  - relationship_advice
  - rickandmorty
  - ripple
  - robinhood
  - skincareaddiction
  - smashbros
  - stardustcrusaders
  - starwars
  - stellaris
  - talesfromthefrontdesk
  - talesfromyourserver
  - thedivision
  - thetruthishere
  - undertale
  - unethicallifeprotips
  - vancouver
  - vive
  - warframe
  - westworld
  - wwe
  - xxfitness
  - yogscast
  - yugioh
all_subreddits:
  - 1200isplenty
  - 2007scape
  - 2healthbars
  - 3amjokes
  - 3dprinting
  - 3ds
  - absoluteunits
  - accidentalrenaissance
  - accidentalwesanderson
  - accounting
  - actuallesbians
  - adhd
  - adventuretime
  - advice
  - ainbow
  - alienblue
  - ama
  - amd
  - americanhorrorstory
  - amitheasshole
  - amiugly
  - analog
  - android
  - androidapps
  - androiddev
  - androidthemes
  - animalcrossing
  - animalsbeingbros
  - animalsbeingderps
  - animalsbeingjerks
  - animalsthatlovemagic
  - anime
  - anime_irl
  - animesuggest
  - announcements
  - anormaldayinrussia
  - answers
  - anxiety
  - apolloapp
  - apple
  - applewatch
  - aquariums
  - archerfx
  - architecture
  - arduino
  - arresteddevelopment
  - arrow
  - art
  - artfundamentals
  - asianbeauty
  - askculinary
  - askdocs
  - askengineers
  - askhistorians
  - askmen
  - askmenover30
  - askphilosophy
  - askreddit
  - askscience
  - asksciencefiction
  - askwomen
  - askwomenadvice
  - asmr
  - asoiaf
  - assassinscreed
  - assholedesign
  - astronomy
  - astrophotography
  - atheism
  - atlanta
  - audioengineering
  - audiophile
  - austin
  - autodetailing
  - autos
  - aviation
  - awesome
  - awesomecarmods
  - awwducational
  - awwnime
  - babybumps
  - backpacking
  - baconreader
  - badhistory
  - baking
  - barkour
  - baseball
  - batman
  - battlefield
  - battlefield_one
  - battlefieldv
  - battlestations
  - bayarea
  - bbq
  - beamazed
  - beer
  - beermoney
  - beforenafteradoption
  - beta
  - bettercallsaul
  - bicycling
  - bigbrother
  - bindingofisaac
  - biology
  - birbs
  - birdswitharms
  - bitcoin
  - bitcoinmarkets
  - bjj
  - blackdesertonline
  - blackmirror
  - blackops4
  - blender
  - blep
  - blog
  - bloodborne
  - blop
  - blunderyears
  - bmw
  - boardgames
  - bobsburgers
  - bodybuilding
  - bodyweightfitness
  - bojackhorseman
  - bokunoheroacademia
  - boneappletea
  - books
  - booksuggestions
  - borderlands
  - bossfight
  - boston
  - boxing
  - breadit
  - breadstapledtotrees
  - breakingbad
  - breath_of_the_wild
  - breathinginformation
  - britishproblems
  - brogress
  - brooklynninenine
  - brushybrushy
  - btc
  - buddhism
  - budgetfood
  - buildapc
  - buildapcsales
  - bulletjournal
  - bundesliga
  - business
  - buyitforlife
  - c25k
  - calligraphy
  - callofduty
  - calvinandhobbes
  - camping
  - campingandhiking
  - campinggear
  - canada
  - cars
  - cartalk
  - casualconversation
  - casualuk
  - catastrophicfailure
  - catloaf
  - catpranks
  - cats
  - catsareassholes
  - catsareliquid
  - catsisuottatfo
  - catslaps
  - catsstandingup
  - cfb
  - cgpgrey
  - changemyview
  - chelseafc
  - chemistry
  - chess
  - chicago
  - childfree
  - childrenfallingover
  - china
  - christianity
  - churning
  - cinemagraphs
  - circleoftrust
  - citiesskylines
  - civ
  - clashofclans
  - clashroyale
  - classicalmusic
  - climbing
  - cocktails
  - coding
  - codzombies
  - coffee
  - cogsci
  - college
  - collegebasketball
  - coloringcorruptions
  - colorizedhistory
  - comicbooks
  - comics
  - community
  - competitivehs
  - competitiveoverwatch
  - compsci
  - confession
  - confessions
  - confusing_perspective
  - contagiouslaughter
  - cooking
  - cookingforbeginners
  - coolguides
  - cordcutters
  - corgi
  - cosplay
  - cozyplaces
  - crackwatch
  - crafts
  - crappydesign
  - crappyoffbrands
  - creepy
  - creepypasta
  - cricket
  - criticalrole
  - crossfit
  - crusaderkings
  - crypto
  - cryptocurrency
  - cryptomarkets
  - cscareerquestions
  - csgo
  - csharp
  - curledfeetsies
  - curlyhair
  - cyberpunk
  - cyberpunkgame
  - daddit
  - dadjokes
  - dadreflexes
  - dailyprogrammer
  - damnthatsinteresting
  - darksouls
  - darksouls2
  - datahoarder
  - dataisbeautiful
  - datascience
  - dating_advice
  - dayz
  - dbz
  - dbzdokkanbattle
  - dc_cinematic
  - dccomics
  - ddlc
  - deadbydaylight
  - deals
  - decidingtobebetter
  - delightfullychubby
  - denver
  - depression
  - depthhub
  - design
  - desirepath
  - destiny2
  - destinythegame
  - diablo
  - diablo3
  - digitalnomad
  - discordapp
  - disney
  - diy
  - dmacademy
  - dnd
  - dndbehindthescreen
  - dndnext
  - doctorwho
  - documentaries
  - doesanybodyelse
  - dogberg
  - dogs
  - dogswithjobs
  - dogtraining
  - donaldglover
  - dontdeadopeninside
  - dota2
  - dragonage
  - drunkorakid
  - dubstep
  - dundermifflin
  - dungeonsanddragons
  - eagles
  - eatcheapandhealthy
  - eatsandwiches
  - edc
  - edm
  - elderscrolls
  - elderscrollsonline
  - electronic_cigarette
  - electronicmusic
  - electronics
  - elitedangerous
  - empiredidnothingwrong
  - emulation
  - engineering
  - engineeringstudents
  - enhancement
  - entertainment
  - entrepreneur
  - ethereum
  - ethtrader
  - eu4
  - europe
  - eve
  - everymanshouldknow
  - everythingscience
  - evilbuildings
  - excel
  - exmormon
  - explainlikeiama
  - explainlikeimfive
  - facepalm
  - factorio
  - fakealbumcovers
  - familyguy
  - fancyfollicles
  - fantasy
  - fantasyfootball
  - fantasypl
  - fantheories
  - fashion
  - fashionreps
  - fasting
  - femalefashionadvice
  - feminism
  - ffxiv
  - fifa
  - fifthworldproblems
  - filmmakers
  - finalfantasy
  - finance
  - financialindependence
  - findareddit
  - fireemblem
  - fireemblemheroes
  - firefly
  - firstworldproblems
  - fishing
  - fitmeals
  - fitness
  - flashtv
  - flexibility
  - flipping
  - floof
  - food
  - foodforthought
  - foodhacks
  - footballhighlights
  - forbiddensnacks
  - foreveralone
  - forhire
  - forhonor
  - fortnite
  - fortnitebattleroyale
  - fortnitebr
  - fortnitecompetitive
  - fountainpens
  - frankocean
  - freebies
  - freeebooks
  - freefolk
  - freegamesonsteam
  - frisson
  - frugal
  - frugalmalefashion
  - funhaus
  - funny
  - futurama
  - futurology
  - gadgets
  - gainit
  - gamecollecting
  - gamedeals
  - gamedev
  - gamegrumps
  - gameofthrones
  - gamephysics
  - gamernews
  - games
  - gaming
  - gardening
  - gaymers
  - germany
  - getdisciplined
  - getmotivated
  - glitch_art
  - globaloffensivetrade
  - golf
  - google
  - googlehome
  - googlepixel
  - gorillaz
  - graffiti
  - grandtheftautov
  - graphic_design
  - gravityfalls
  - greenbaypackers
  - grilledcheese
  - groestlcoin
  - gtaonline
  - gtav
  - guildwars2
  - guitar
  - gunners
  - hacking
  - halo
  - handwriting
  - happy
  - happycrowds
  - happycryingdads
  - hardcoreaww
  - hardware
  - hardwareswap
  - harrypotter
  - headphones
  - health
  - healthyfood
  - heavymind
  - heavyseas
  - help
  - heroesofthestorm
  - hfy
  - hiking
  - himym
  - hiphopheads
  - hitmanimals
  - hmmm
  - holdmybeer
  - holdmycatnip
  - holdmyjuicebox
  - holdmyredbull
  - homeautomation
  - homebrewing
  - homeimprovement
  - homelab
  - homestead
  - horror
  - houston
  - howto
  - howtohack
  - humansbeingbros
  - humor
  - iama
  - iasip
  - idiotsincars
  - ifyoulikeblank
  - iiiiiiitttttttttttt
  - ilikthebred
  - illegallifeprotips
  - imaginarycharacters
  - imaginarylandscapes
  - imaginaryleviathans
  - imaginarymaps
  - imaginarymonsters
  - imaginarytechnology
  - india
  - indiegaming
  - indieheads
  - instant_regret
  - interiordesign
  - intermittentfasting
  - internetisbeautiful
  - introvert
  - investing
  - iota
  - iphone
  - ireland
  - itookapicture
  - itsaunixsystem
  - iwanttolearn
  - jailbreak
  - japan
  - japanesegameshows
  - japantravel
  - javascript
  - jazz
  - jobs
  - joerogan
  - jokes
  - justnomil
  - justrolledintotheshop
  - kanye
  - karmacourt
  - keming
  - kendricklamar
  - keto
  - ketogains
  - ketorecipes
  - kingdomhearts
  - kitchenconfidential
  - knitting
  - knives
  - kpop
  - lakers
  - languagelearning
  - latinacuties
  - leagueoflegends
  - leangains
  - learnart
  - learnjapanese
  - learnmath
  - learnprogramming
  - learnpython
  - learnuselesstalents
  - legaladvice
  - lego
  - letsnotmeet
  - lgbt
  - lifehacks
  - lifeprotips
  - likeus
  - linguistics
  - linux
  - linux4noobs
  - linuxadmin
  - linuxmasterrace
  - listentothis
  - litecoin
  - literature
  - liverpoolfc
  - livestreamfail
  - lockpicking
  - lolcats
  - london
  - losangeles
  - loseit
  - lotr
  - luciddreaming
  - mac
  - machinelearning
  - mademesmile
  - magicarena
  - magictcg
  - makenewfriendshere
  - makeupaddiction
  - makinghiphop
  - malefashion
  - malefashionadvice
  - malehairadvice
  - malelifestyle
  - malelivingspace
  - maliciouscompliance
  - manga
  - marijuana
  - marketing
  - marvel
  - marvelstudios
  - mashups
  - masseffect
  - masterreturns
  - math
  - maybemaybemaybe
  - me_irl
  - mealprepsunday
  - mechanicalkeyboards
  - medicalschool
  - medicine
  - meditation
  - melbourne
  - metal
  - metalgearsolid
  - mexico
  - microgrowery
  - mildlyinteresting
  - military
  - millionairemakers
  - miniworlds
  - misleadingthumbnails
  - mlem
  - mls
  - mma
  - mmorpg
  - modelmakers
  - modnews
  - monero
  - monsterhunter
  - monsterhunterworld
  - montageparodies
  - mostbeautiful
  - moviedetails
  - moviesinthemaking
  - moviesuggestions
  - mrrobot
  - mtb
  - museumofreddit
  - music
  - musictheory
  - mycology
  - naruto
  - nasa
  - nascar
  - natureismetal
  - naturewasmetal
  - nba
  - nba2k
  - needadvice
  - neo
  - netflix
  - netflixbestof
  - netsec
  - networking
  - nevertellmetheodds
  - newreddits
  - news
  - newzealand
  - nfl
  - nhl
  - nintendo
  - nintendoswitch
  - nintendoswitchdeals
  - node
  - nomansskythegame
  - nonononoyes
  - nosleep
  - nostalgia
  - nostupidquestions
  - notinteresting
  - nottheonion
  - nottimanderic
  - nutrition
  - nvidia
  - nyc
  - obscuremedia
  - occult
  - oculus
  - oddlysatisfying
  - offlinetv
  - offmychest
  - okcupid
  - oldschoolcool
  - onejob
  - onepiece
  - oneplus
  - onetruegod
  - onions
  - osha
  - osugame
  - outdoors
  - outoftheloop
  - outrun
  - outside
  - overwatch
  - overwatchuniversity
  - painting
  - paleo
  - pandr
  - paradoxplaza
  - paranormal
  - pareidolia
  - parenting
  - partyparrot
  - pathofexile
  - patientgamers
  - patriots
  - pcgaming
  - pcmasterrace
  - perfectfit
  - perfectloops
  - perfecttiming
  - personalfinance
  - personalfinancecanada
  - petthedamndog
  - pettyrevenge
  - pewdiepiesubmissions
  - philadelphia
  - philosophy
  - photocritique
  - photography
  - photoshop
  - photoshopbattles
  - php
  - physics
  - piano
  - pitbulls
  - pixelart
  - pizza
  - playrust
  - playstation
  - plex
  - podcasts
  - poetry
  - pokemon
  - pokemongo
  - poker
  - polyamory
  - portland
  - powerlifting
  - praisethecameraman
  - prettygirls
  - productivity
  - programmerhumor
  - programming
  - projectcar
  - protectandserve
  - ps4
  - ps4deals
  - psychology
  - psychonaut
  - pubattlegrounds
  - pubg
  - punny
  - puns
  - puppysmiles
  - python
  - quotes
  - rabbits
  - radiohead
  - raining
  - rainmeter
  - raisedbynarcissists
  - ramen
  - rarepuppers
  - raspberry_pi
  - rateme
  - rbi
  - reactjs
  - realestate
  - reallifedoodles
  - reallifeshinies
  - recipes
  - reddeadredemption
  - reddeadredemption2
  - reddevils
  - reddit.com
  - redditgetsdrawn
  - redditlaqueristas
  - redditsync
  - relationship_advice
  - relationships
  - relayforreddit
  - repsneakers
  - retrofuturism
  - reverseanimalrescue
  - rickandmorty
  - rimworld
  - ripple
  - roadcam
  - roadtrip
  - roastme
  - robinhood
  - rocketleague
  - roosterteeth
  - rpg
  - runescape
  - running
  - sanfrancisco
  - sbubby
  - science
  - scifi
  - scp
  - screenwriting
  - seattle
  - secretsanta
  - seinfeld
  - self
  - selfimprovement
  - serialkillers
  - seriouseats
  - sewing
  - sherlock
  - shield
  - shingekinokyojin
  - shoestring
  - shortscarystories
  - shouldibuythisgame
  - showerthoughts
  - shutupandtakemymoney
  - siliconvalleyhbo
  - simpleliving
  - simulated
  - singapore
  - skateboarding
  - sketchdaily
  - skiing
  - skincareaddiction
  - skyrim
  - skyrimmods
  - slowcooking
  - smallbusiness
  - smashbros
  - smashbrosultimate
  - smite
  - snaplenses
  - sneakers
  - sneks
  - snowboarding
  - soccer
  - socialanxiety
  - socialengineering
  - socialskills
  - softwaregore
  - solotravel
  - somethingimade
  - southpark
  - space
  - spacex
  - specart
  - specializedtools
  - speedrun
  - splatoon
  - spop
  - sportsarefun
  - spotify
  - squaredcircle
  - standupcomedy
  - standupshots
  - starcraft
  - stardewvalley
  - stardustcrusaders
  - startledcats
  - startups
  - starwars
  - starwarsbattlefront
  - steam
  - steamdeals
  - stellar
  - stellaris
  - stevenuniverse
  - stockmarket
  - stocks
  - stoicism
  - stopdrinking
  - stoppedworking
  - strangerthings
  - streetwear
  - stuffoncats
  - subaru
  - submechanophobia
  - succulents
  - suggestmeabook
  - summonerschool
  - superbowl
  - supernatural
  - supremeclothing
  - survival
  - sweatypalms
  - swtor
  - sysadmin
  - talesfromcallcenters
  - talesfromretail
  - talesfromtechsupport
  - talesfromthecustomer
  - talesfromthefrontdesk
  - talesfromthepizzaguy
  - talesfromyourserver
  - tattoos
  - tea
  - teachers
  - technicallythetruth
  - technology
  - techsupport
  - techsupportmacgyver
  - teefies
  - teenagers
  - television
  - tennis
  - terraria
  - teslamotors
  - texas
  - tf2
  - thalassophobia
  - thebutton
  - thecatdimension
  - thedepthsbelow
  - thedivision
  - thegirlsurvivalguide
  - thegrandtour
  - thelastairbender
  - themonkeyspaw
  - theocho
  - thesilphroad
  - thesimpsons
  - thesims
  - thetruthishere
  - thewalkingdead
  - thewaywewere
  - theydidthemath
  - thingsforants
  - thisismylifemeow
  - thriftstorehauls
  - tifu
  - tiltshift
  - tinyhouses
  - tipofmytongue
  - tippytaps
  - titanfall
  - tldr
  - todayilearned
  - tooafraidtoask
  - topgear
  - toptalent
  - toronto
  - totalwar
  - trackers
  - trailerparkboys
  - trap
  - trashpandas
  - travel
  - trueaskreddit
  - truefilm
  - truegaming
  - trueoffmychest
  - tuckedinkitties
  - twitch
  - typography
  - ubuntu
  - ufc
  - ultralight
  - unbgbbiivchidctiicbg
  - undertale
  - unethicallifeprotips
  - unexpected
  - unity3d
  - unresolvedmysteries
  - unsentletters
  - unsolvedmysteries
  - upliftingnews
  - urbanexploration
  - vagabond
  - vancouver
  - vandwellers
  - vaping
  - vaporents
  - vaporwave
  - vaporwaveaesthetics
  - vegan
  - veganrecipes
  - vegetarian
  - vexillology
  - vinyl
  - vive
  - wallstreetbets
  - warframe
  - warhammer
  - warhammer40k
  - warriors
  - watchandlearn
  - watches
  - wearethemusicmakers
  - web_design
  - webcomics
  - webdev
  - webgames
  - weddingplanning
  - weightroom
  - wellthatsucks
  - wellworn
  - westworld
  - whatcouldgowrong
  - whatisthisthing
  - whatsinthisthing
  - whatsthisbug
  - whatsthisplant
  - whatswrongwithyourdog
  - wheredidthesodago
  - whowouldwin
  - whyweretheyfilming
  - wicked_edge
  - wiiu
  - wikipedia
  - wildernessbackpacking
  - windows
  - windows10
  - woahdude
  - woodworking
  - woof_irl
  - woooosh
  - workonline
  - worldbuilding
  - worldcup
  - worldnews
  - wouldyourather
  - wow
  - writing
  - writingprompts
  - wwe
  - wwii
  - xboxone
  - xkcd
  - xxfitness
  - yesyesyesno
  - yesyesyesyesno
  - yoga
  - yogscast
  - youshouldknow
  - yugioh
  - zelda
  - zenhabits
  - zerowaste
  - zombies
  - zoomies